{% set name = "sphinx-proof" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx-proof-{{ version }}.tar.gz
  sha256: db938da1ea18880f80f0e979cb895604a490beff3e8f3dd1945d4997451b373b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - docutils >=0.15
    - sphinx
    - sphinx-book-theme

test:
  imports:
    - sphinx_proof
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/sphinx-proof
  summary: A Sphinx extension for producing proofs, theorems, axioms, etc.
  dev_url: https://github.com/executablebooks/sphinx-proof
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
